### ISSUE TITLE
Publish WaveLogGate in Arch User Repository

### ISSUE THREAD

**Issue by 205er** [wavelog/WaveLogGate#14]
Hi all,

I am using Manjaro and want to try out WaveLogGate. Any chance that you'll add this nice piece of software to the [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository)?

br

**Comment by kbabioch** [comment]
Isn't this something that should be picked up by a fellow Arch Linux user ;-)? Packaging stuff for AUR is pretty straight forward, maybe you want to give it a try yourself?

**Comment by 205er** [comment]
Indeed, I already thought about doing this on my own, but I have no glue where to start ;-)
If I'll find some time to read through the documentation and if the task is doable for me, I'll give it a try.

**Comment by fabianfrz** [comment]
Now you have a nice template to work with:

https://aur.archlinux.org/packages/waveloggate-git

**Comment by 205er** [comment]
Thanks Fabian!!!
