### ISSUE TITLE
"Received broken ADIF" from WSJT-Z

### ISSUE THREAD

**Issue by gx1400** [wavelog/WaveLogGate#20]
All of the qso logs from WSJT-Z top up in my WLGate as "Received broken ADIF"

Are there application logs available?  The only logs I see in C:\Users\\[user]\AppData\Local\WLGate_by_DJ7NT\ are for squirrel

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ADIF parsing logic to handle potential format variations from WSJT-Z. Added error logging for debugging purposes.

You can review changes in this commit: https://github.com/mnmnk43434/wavelog-WaveLogGate-20/commit/a6049a0a5dd2e06a150dd40c049ad20f64b7852b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by gx1400** [comment]
in case the ampersand is an issue

```xml
<call:4>K5VV <gridsquare:0> <mode:3>FT8 <rst_sent:3>-14 <rst_rcvd:3>+05 <qso_date:8>20241129 <time_on:6>151045 <qso_date_off:8>20241129 <time_off:6>151215 <band:3>20m <freq:9>14.077043 <station_callsign:4>NZ0P <my_gridsquare:6>EM28PX <tx_pwr:3>30W <comment:30>IC7300 and DX-EE attic antenna <eor>
```

**Comment by HB9HIL** [comment]
It's likely you entered `30W` in TX Power. 

Try setting only `30`

**Comment by gx1400** [comment]
> It's likely you entered `30W` in TX Power.
> 
> Try setting only `30`

That was it! Thanks
