### ISSUE TITLE
Notarize/ Sign MacOS Application

### ISSUE THREAD

**Issue by zone11** [wavelog/WaveLogGate#3]
I would recommend to Notarize/Sign the MacOS binary releases. It works flawless with your existing electron-forge environment.
If you don't have an Apple developer account, I can offer to do that for you and contribute.

73 de HB9HJQ

**Comment by int2001** [comment]
I am really thankful for that. 
But i don't want the Tool signed by another ham/dev for various reasons.

You can simply disable the snakeoil-cert check in MacOs within the settings, like at many other open source projects.

Maybe we are going to fetch an own certificate later. But as long as Apple allows unsigned apps, there's no real need for that.

Yep, it may look more professional, but Wavelog (and in this case WavelogGate) is still a hobbyproject. 

BTW: Contribution is always welcome, if you have improvements for the Tool itself.

PS: My personal(!) opinion about that signing stuff: it's for Apple/Microsoft to earn money. It's not a proof that the software is "secure" or free from malware.

**Comment by zone11** [comment]
Of course I can understand that.

I was primarily concerned with the inexperienced users who stumble over such simple steps as deactivating Gatekeeper.
Often seen with other projects.

Thank you for your work!
