### ISSUE TITLE
UDP sends incorrect time 

### ISSUE THREAD

**Issue by spREGR** [wavelog/WaveLogGate#5]
During the IOTA contest, I connected N1MM do WavelogGate via UDP. The logs posted on WaveLog side is incorrect time (few hours in the past)

**Comment by HB9HIL** [comment]
Hello @spREGR 

Sorry for the delay. I have some more questions

- If you try to reproduce the issue now, does it still persist?
- Which timezone is set on your computer?
- Which timezone is set on N1MM?
- Which timezone is set on Wavelog?

I never saw this issue before and it's probably just a settings issue between these three endpoints.

**Comment by spREGR** [comment]
Sorry, I was travelling and couldn't conduct the tests
If you try to reproduce the issue now, does it still persist? ==> Yes, current time is 22:30 UTC and Wavelog recorded 17:00 UTC via UDP 
Which timezone is set on your computer? UTC +5:30
Which timezone is set on N1MM? UTC
Which timezone is set on Wavelog? UTC

**Comment by HB9HIL** [comment]
Okay I was able to reproduce this issue. 

N1MM does export a QSO not as ADIF but as XML

Therefore it does not have the ADIF specific tags `date_on` or `time_on` but a `timestamp` tag which does not correctly get parsed in WLgate

<img width="355" alt="image" src="https://github.com/user-attachments/assets/c1c81d63-ed32-4966-ae4f-fa89bf335123">

I will take a look with @int2001 about this. In the meantime you can workaround this by setting the timezone of your computer to UTC aswell.
