### ISSUE TITLE
Wrong release architecture

### ISSUE THREAD

**Issue by lostkira** [wavelog/WaveLogGate#6]
Version 1.0.16, universal build for MacOS that is actually for Apple chips.

**Comment by HB9HIL** [comment]
Hello @lostkira 

I think you are right. Have to see where the issue is. I will inform you when the correct architecture is available.

**Comment by HB9HIL** [comment]
hello @lostkira 

this issue should be fixed now. I recreated the release so the binaries should be correct now. 

Please test the MacOS universal package and close this issue if it works as expected. Thanks for reporting :)

https://github.com/wavelog/WaveLogGate/releases/tag/v1.0.16

**Comment by lostkira** [comment]
works perfect now! Thanks for your hard work
